create table if not exists public.timeline_games (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null default '',
  source_prompt text,
  is_published boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.timeline_game_events (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.timeline_games(id) on delete cascade,
  year integer not null,
  event text not null,
  sort_order integer not null default 1,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists timeline_games_slug_idx on public.timeline_games(slug);
create index if not exists timeline_games_published_idx on public.timeline_games(is_published, updated_at desc);
create index if not exists timeline_game_events_game_idx on public.timeline_game_events(game_id, sort_order asc);

alter table public.timeline_games enable row level security;
alter table public.timeline_game_events enable row level security;

drop policy if exists "Public can read published timeline games" on public.timeline_games;
create policy "Public can read published timeline games"
  on public.timeline_games
  for select
  using (is_published = true);

drop policy if exists "Public can read events for published timeline games" on public.timeline_game_events;
create policy "Public can read events for published timeline games"
  on public.timeline_game_events
  for select
  using (
    exists (
      select 1
      from public.timeline_games
      where timeline_games.id = timeline_game_events.game_id
        and timeline_games.is_published = true
    )
  );
